name: baches_y_topes
description: A mobile app for reporting potholes and speed bumps
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  speech_to_text: ^7.3.0
  flutter_tts: ^3.8.3
  shared_preferences: ^2.2.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/bache.png
    - assets/tope.png
    - assets/app_icon.png
    - assets/app_icon_fg.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon_fg.png"
  adaptive_icon_background: "#000000"
